name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install uv
      run: |
        wget -qO- https://astral.sh/uv/install.sh | sh

    - name: PyInstaller Linux
      # You may pin to the exact commit or the version.
      # uses: JackMcKew/pyinstaller-action-linux@38639c352a36917eea765f9283bfd1092c28af7b
      uses: JackMcKew/pyinstaller-action-linux@0.1.4
      with:
        # Directory containing source code & .spec file (optional requirements.txt).
        path: ./
          

    - name: Install dependencies with uv
      run: |
        uv pip install -r pyproject.toml --system

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest
